# Generated by Django 5.0.3 on 2024-05-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User3',
        ),
    ]
