# Generated by Django 5.0.3 on 2024-05-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prediction_app', '0002_alter_diabetesprediction_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User3',
            new_name='User',
        ),
    ]
