# Generated by Django 5.0.3 on 2024-05-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_user3_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
