# Generated by Django 5.0.3 on 2024-05-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_profile_user_type_profile_is_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
