# Generated by Django 5.0.3 on 2024-04-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appim', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='image',
            new_name='image_url',
        ),
    ]
