# Generated by Django 5.0.3 on 2024-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appim', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
