# Generated by Django 5.0.3 on 2024-05-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appim', '0006_alter_appointment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
